### ISSUE TITLE
Windows search is painfully slow

### ISSUE THREAD

**Issue by gegutierrezneri** [microsoft/Windows-Dev-Performance#8]
In frustration I've disabled searching and system indexing (as it also arbitrarily decides to consume a lot of CPU resources) and only rely on [Everything](https://www.voidtools.com/) whenever I need to look for files within Windows.

**Comment by mylemans** [comment]
Last time I used the windows search (and was ok with it) was when I had Windows XP

Currently I use Locate32 for all my search needs.

**Comment by pablojimpas** [comment]
Being used to tools like [fd](https://github.com/sharkdp/fd) or [fzf](https://github.com/junegunn/fzf) in Linux makes Windows Search speed laughable, it's bloated with web results and other stuff which isn't relevant when trying to search in my computer.

**Comment by WSLUser** [comment]
> it's bloated with web results and other stuff which isn't relevant

you can disable it easily. But it's still quiite slow, making it so opening apps or trying to access their properties via right click within the Start Menu is takes too much time just to search it up. Something I found helps slightly for me is returning the Win7 start menu using OpenShell as it provides better navigation.

**Comment by orcmid** [comment]
Out of curiosity, are we talking about Windows Search with indexing enabled, or without indexing enabled?  (Or is there even such a choice on Windows 10?)

**Comment by WSLUser** [comment]
If you've enabled file indexing for the entire filesystem, there's still a cost. Now you've got a cache. That cache works better directly in File Explorer than Windows Search and still can be slow when you store enough data, slower still if the disk is just about out of space.

**Comment by bitcrazed** [comment]
Polite ask: 

## Please complete the template and follow its guidance when filing issues

The issue as described offers no repro steps, no comparative measurements, no examples, no screenshots.

As such, there's VERY little to help us figure out WHAT the problem is, what it's root cause is, nor how we might fix it.

We do know that there could indeed be improvements in how Windows indexes and searches for local content, but we need details as to what YOU'RE seeing so that we can repro and explore.

**Comment by bitcrazed** [comment]
Closing due to no author feedback.

**Comment by Poopooracoocoo** [comment]
and even the people who created PowerToys Run know that Wox (or Flow Launcher) with Everything is much better. They couldn't concede to how great Everything is though. I'm sure indexing isn't the culprit here. It's the UI, which also happens to be web based >:( and the stupid web searches that cannot be turned off without regedit that also disables calculations.

**Comment by zakius** [comment]
Wox is also incredibly slow when compared to Keypirinha
and in my experience even when compared to windows app search in start

**Comment by Eli-Black-Work** [comment]
@bitcrazed, Would you mind reopening this, so we can have people post more detailed information? This issue has 38 likes, so I think there's a fair amount of interest 🙂

I did some testing. Results below 🙂

I have a 190MB unindexed directory on my drive that has 897 files and 291 folders in it. The folder is not indexed by Windows Search.

Using Windows Search to search for the word "test" in the folder takes 6 seconds. Search options used:
- Search in all subfolders
- Advanced options -> In non-index locations -> ✅ File contents (checked)
- Advanced options -> In non-index locations -> ✅ System files (checked)
- Advanced options -> In non-index locations -> ✖ Zipped (compressed) folders (unchecked)

Using [File Locator Lite](https://www.mythicsoft.com/filelocatorlite/download/) to search for the word "test" in both filenames and file contents takes 2 seconds. File Locator Lite doesn't use a search index.

Please let me know what other information I can post that would be helpful 🙂

**Comment by batzen** [comment]
@Bosch-Eli-Black Maybe you want to try [Batzendev.Tools](https://chocolatey.org/packages/Batzendev.Tools) (my own tool) if you want fast content search, at least in text files. It uses no index, is written in C#, and it takes < 1 sec (~800 ms) to search through all of the dotnet runtime source code (content filter "ForkAndExecProcess", extension filter = *.cs = ~40 000 files ~ 450 MB), including encoding detection for every file.
Just searching for the files takes ~200 ms (filtering for *.cs out of 135 660 files and 21.202 directories).
Currently my tool only supports searching for text in files, but i plan to add a pure file search in the future.

The point is: 
Searching, even without any index, can be blazingly fast and i never understood why the explorer or start menu search is so slow. Searching for "*.cs" with explorer takes ~9 sec just to find the files...
Searching for "ForkAndExecProcess ext:cs" with explorer takes ~170 sec, that's at least 170 times slower than my tool...

**Comment by bitcrazed** [comment]
Reopening on request.

Assigning to @axelandrejs who's dev lead for Indexer and more knowledgeable about how search works than I am.

**Comment by bitcrazed** [comment]
Okay. Have discussed with Axel.

Indexer "consuming too much CPU" is a known issue, is fixed and is shipping in Insider builds, and will also ship in the next desktop OS refresh. The Indexer has received several improvements which result in it backing-off gracefully if the machine gets busy, and avoids unnecessary index-scans in the first place.

> FWIW: I've enabled the "Enhanced" (i.e. index everything mode) Find My Files setting on all my machines for the last several months and have never been impeded by Indexer eating the CPU when the machine was busy with other work.
> ![image](https://user-images.githubusercontent.com/961950/103689831-adf9c900-4f48-11eb-9452-ddc88772c812.png)

The Indexing, Search, and Shell teams also have a bunch of additional improvements and enhancements queued up for future OS updates too which should result in substantial search perf improvements, and overhead & latency reduction.

### ⚠ Note
The observations above about disabling indexing and then noting that search perf isn't as good as a dedicated search tools (most of which work by building in-memory or on-disk indexes of their own) shouldn't be a surprise.

**Comment by mylemans** [comment]
> Okay. Have discussed with Axel.
> 
> Indexer "consuming too much CPU" is a known issue, is fixed and is shipping in Insider builds, and will also ship in the next desktop OS refresh. The Indexer has received several improvements which result in it backing-off gracefully if the machine gets busy, and avoids unnecessary index-scans in the first place.
> 
> > FWIW: I've enabled the "Enhanced" (i.e. index everything mode) Find My Files setting on all my machines for the last several months and have never been impeded by Indexer eating the CPU when the machine was busy with other work.
> > ![image](https://user-images.githubusercontent.com/961950/103689831-adf9c900-4f48-11eb-9452-ddc88772c812.png)
> 
> The Indexing, Search, and Shell teams also have a bunch of additional improvements and enhancements queued up for future OS updates too which should result in substantial search perf improvements, and overhead & latency reduction.
> 
> ### ⚠ Note
> The observations above about disabling indexing and then noting that search perf isn't as good as a dedicated search tools (most of which work by building in-memory or on-disk indexes of their own) shouldn't be a surprise.

Wouldn't it be possible (or is it already?) to use some cli command to do a full (or partial) index and see the result? Instead of working 'in the background'?

**Comment by axelandrejs** [comment]
If you query for something that is not currently up-to-date we will index that particular scope on-demand. But the performance of this is obviously slow.

Our main focus recently has been to get the indexer out of your way. We have ideas for improving performance as well, but it is too early to talk about them.

**Comment by Eli-Black-Work** [comment]
Thanks for the replies! Sounds like this may be a case where we need to wait until a future OS update before returning to this topic 🙂

**Comment by Bosch-Eli-Black** [comment]
[not stale]

**Comment by Poopooracoocoo** [comment]
here's some activity: windows search is trash 🙃

**Comment by bitcrazed** [comment]
@Poopooracoocoo While you may think it's funny, it's not. Please keep your comments respectful and constructive.

**Comment by Eli-Black-Work** [comment]
@bitcrazed, Can we remove the "Needs-Author-Feedback" tag?

**Comment by bitcrazed** [comment]
Great catch - thanks. Have added the investigating tag because the team have some ideas of additional improvements they may be able to make beyond those that are already in the pipe/planned for the next couple of iterations.

**Comment by Eli-Black-Work** [comment]
Thanks!

I'm mostly just hoping that removing that tag makes the msftbot stale warnings go away 😁

**Comment by bitcrazed** [comment]
Hey all. Closing this issue for now since the indexing team have already shipped several important improvements in 20H2 which is now generally available. If you find further issues, please report via Feedback Hub so the team gets info on your machine, resources, and workload, so that they can figure out what's going on.

Thanks for reporting and contributing to this interesting discussion!
